# Generated by Django 4.2.20 on 2025-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_coderef'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetailAppro',
            new_name='EntreeItems',
        ),
        migrations.RenameModel(
            old_name='DetailSortie',
            new_name='SortieItems',
        ),
        migrations.RemoveField(
            model_name='entree',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='sortiestock',
            name='product',
        ),
        migrations.AddField(
            model_name='entree',
            name='libelle',
            field=models.CharField(default=1, max_length=255, verbose_name="Libellé d'entrée"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortiestock',
            name='libelle',
            field=models.CharField(default=1, max_length=255, verbose_name='Libellé de sortie'),
            preserve_default=False,
        ),
    ]
