# Generated by Django 4.2.20 on 2025-04-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_detailappro_entreeitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeitems',
            name='entree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.entree'),
        ),
    ]
