# Generated by Django 4.2.20 on 2025-04-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_coderef'),
        ('stock', '0003_alter_entreeitems_entree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='entreeitems',
            name='qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
