# Generated by Django 4.2.20 on 2025-04-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_coderef'),
        ('stock', '0004_alter_entreeitems_product_alter_entreeitems_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreeitems',
            name='entree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.entree'),
        ),
        migrations.AlterField(
            model_name='entreeitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='entreeitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
