# Generated by Django 5.1.7 on 2025-03-25 09:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeRef', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(6), django.core.validators.MaxLengthValidator(6)], verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, unique=True, verbose_name='Libellé article')),
                ('productType', models.CharField(choices=[('Produit simple', 'Produit simple'), ('Produit varié', 'Produit varié')], max_length=50, verbose_name='Type de produit')),
                ('stockAlert', models.IntegerField(blank=True, default=5, null=True, verbose_name='Stock alerte')),
                ('qtyStock', models.SmallIntegerField(default=0, verbose_name='Qté en stock')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Déscription')),
                ('qteEnVente', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Qté en vente')),
                ('canExpiried', models.BooleanField(default=False)),
                ('expiried_on', models.DateField(blank=True, null=True)),
                ('barreCode', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(16)], verbose_name='Barre Code')),
                ('status', models.CharField(choices=[('Activé', 'Activé'), ('Désactivé', 'Désactivé'), ('Expiré', 'Expiré')], default='Activé', max_length=10, verbose_name='Statut')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categorie')),
                ('unity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unity.unitevente')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 't_Product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductCodeBarre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeBarre', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'ProductCodeBarre',
                'verbose_name_plural': 'ProductCodeBarres',
                'db_table': 't_ProductCodeBarre',
                'managed': True,
            },
        ),
    ]
