# Generated by Django 5.1.7 on 2025-04-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productType',
        ),
    ]
