# Generated by Django 5.1.7 on 2025-04-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_producttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='canExpiried',
            field=models.CharField(choices=[('EXP', "Oui le produit a une date d'expiration"), ('NOTEXP', "Non le produit n'expire jamais")], max_length=200),
        ),
    ]
