# Generated by Django 5.1.7 on 2025-04-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_canexpiried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='canExpiried',
            field=models.BooleanField(default=False, verbose_name="Produit avec date d'expiration ?"),
        ),
    ]
