# Generated by Django 5.1.7 on 2025-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_canexpiried'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix de vente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='qteEnVente',
            field=models.PositiveIntegerField(default=0, verbose_name='Qté en vente'),
            preserve_default=False,
        ),
    ]
