# Generated by Django 4.2.20 on 2025-04-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={},
        ),
        migrations.AlterModelTable(
            name='categorie',
            table=None,
        ),
    ]
