# Generated by Django 5.1.7 on 2025-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='T800nt8rsKtgTHb7zcwBLLTEb2af583B', editable=False, max_length=32, unique=True),
        ),
    ]
