# Generated by Django 4.2.20 on 2025-04-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ukuqhlvn2JysZcX5dxzwi3zYcsQqDTRN', editable=False, max_length=32, unique=True),
        ),
    ]
