# Generated by Django 4.2.20 on 2025-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gTTj5hJeizFV4NbKRbvHX53VGlSdBXNL', editable=False, max_length=32, unique=True),
        ),
    ]
