# Generated by Django 5.1.7 on 2025-04-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_passwordresetrequest_token_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='k9znW5zGuVup6aSuRsYXsuVpZZ3eslE8', editable=False, max_length=32, unique=True),
        ),
    ]
