# Generated by Django 4.2.20 on 2025-04-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='XMPLnwj89bDfg6otSDkhB0iY8fH7kWrh', editable=False, max_length=32, unique=True),
        ),
    ]
