# Generated by Django 4.2.20 on 2025-04-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Nq80dacttTa26Cp9EzslSiaj4IsF5sQ6', editable=False, max_length=32, unique=True),
        ),
    ]
