# Generated by Django 5.1.7 on 2025-04-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='pvJ78BRQ2Wr0MYeXcbr03LuCizZ8fSoH', editable=False, max_length=32, unique=True),
        ),
    ]
