# Generated by Django 5.1.7 on 2025-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='2wzlgowkXMoODMj6bCjJ8iiIi2aIUDpn', editable=False, max_length=32, unique=True),
        ),
    ]
