# Generated by Django 4.2.20 on 2025-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HIg4BImflb5v6gZuTmPlT3DC4Nm9d9na', editable=False, max_length=32, unique=True),
        ),
    ]
