# Generated by Django 5.1.7 on 2025-04-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='I4LIpM2KPZSszDSs1vmzF0woEUSRqbNf', editable=False, max_length=32, unique=True),
        ),
    ]
