# Generated by Django 4.2.20 on 2025-04-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0Zf3KeWLVcA7gUIyrRAb6k0pbbTKnJEC', editable=False, max_length=32, unique=True),
        ),
    ]
