# Generated by Django 4.2.20 on 2025-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastNum', models.SmallIntegerField(default=0, verbose_name='Dernier Numéro de Facture')),
            ],
            options={
                'verbose_name': 'NumFacture',
                'verbose_name_plural': 'NumFactures',
                'db_table': 't_NumFacture',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='vente',
            name='total_dollar',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vente',
            name='total_franc',
            field=models.IntegerField(default=0),
        ),
    ]
