# Generated by Django 4.2.20 on 2025-04-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vente', '0002_numfacture_alter_vente_total_dollar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('qty', models.IntegerField(default=0)),
                ('prix', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 't_Cart',
                'managed': True,
            },
        ),
    ]
